### ISSUE TITLE
Function names in an ES6 class are not recognized if opening curly brace is on next line

### ISSUE THREAD

**Issue by jonathanwells** [Benvie/JavaScriptNext.tmLanguage#115]
If the opening curly brace is on the same line as the function name, then the function name is correctly parsed. This works fine:

```javascript
class Something {
    doThing() { // doThing will be recognized as a function name
        // code
    }
}
```

This doesn't work correctly:

```javascript
class Something {
    doThing() // doThing will not be recognized as a function name
    { 
        // code
    }
}
```

If I have to work on a codebase with this style, I lose the benefit of jump-to-symbol in Sublime/Textmate or proper syntax highlighting.

**Comment by zertosh** [comment]
It's the same Sublime limitation as described in https://github.com/Benvie/JavaScriptNext.tmLanguage/issues/41#issuecomment-58485199

**Comment by jonathanwells** [comment]
I see. Is this the case with TextMate as well then?

**Comment by simonzack** [comment]
@zertosh is right, it's rather difficult to deal with the multi-line case as multi-line regex matches aren't supported. If you think of a way you're welcome to contribute.

TextMate uses the same tmLanguage spec so the same thing applies. Sublime text has recently introduced proper LL parsing which may improve things here (it still won't parse #41 properly), but that doesn't apply to TextMate.
