### ISSUE TITLE
Really slow on large files?

### ISSUE THREAD

**Issue by thomasmattheussen** [Benvie/JavaScriptNext.tmLanguage#119]
When opening a large file (in my current example 10k lines) the file takes forever to load... This doesn't happen using the default js highlighter.

I'm using Sublime Text 2221

**Comment by petersirka** [comment]
I have same problem but only on large line.
Thanks.

**Comment by zertosh** [comment]
ST2 isn't supported. @petersirka are you also using ST2?

**Comment by petersirka** [comment]
I found the problem. The problem persist when I have enabled `detect slow plugins`.
Everything works correctly.

:100: sorry.

**Comment by simonzack** [comment]
@thomasmattheussen Can you give an example file?

**Comment by thomasmattheussen** [comment]
I've since upgraded to ST3 and not experiencing the problem anymore. 

An example file would just be a large javascript file (like 10k+ loc)...

**Comment by simonzack** [comment]
Well good to know the problem fixed itself, that doesn't happen often :)
