### ISSUE TITLE
Template strings aren't highlighted as strings

### ISSUE THREAD

**Issue by 1000hz** [Benvie/JavaScriptNext.tmLanguage#121]
It seems like template strings aren't being treated as strings.

See below:
![image](https://cloud.githubusercontent.com/assets/1395018/7330319/2279296c-eab2-11e4-8abc-ab509932ee19.png)

As a result, the `//` in the url is being treated as a comment.

**Comment by zertosh** [comment]
You probably have the stock JavaScript syntax selected. I ran a quick test, and this is what your sample looks like using JavaScriptNext:

![zuhbn](https://cloud.githubusercontent.com/assets/830952/7330555/93ffa5be-eabe-11e4-885f-ba00a89468b0.png)

But this is what it looks like using the stock JavaScript syntax:

![mhbia](https://cloud.githubusercontent.com/assets/830952/7330557/a1840da6-eabe-11e4-9477-63998f30ce61.png)

**Comment by 1000hz** [comment]
D'oh, you're right.
