### ISSUE TITLE
I can't find the package on sublime text 2

### ISSUE THREAD

**Issue by joshbedo** [Benvie/JavaScriptNext.tmLanguage#123]
I have all of the updates for Sublime Text 2 and the application is registered with a license but after doing `Install Package` and then searching for `Javascript Next` i see no results. Am i missing a step?

**Comment by Paxa** [comment]
Duplicate #114

**Comment by simonzack** [comment]
No idea, it works fine for me. It's called `JavascriptNext - ES6 syntax` here.

**Comment by joshbedo** [comment]
ahhh I guess i already had it installed >.<
