### ISSUE TITLE
forward slashes in regex screw up highlighting

### ISSUE THREAD

**Issue by lalitkapoor** [Benvie/JavaScriptNext.tmLanguage#126]
the following regx will result in incorrect highlighting for the rest of the document
```javascript
var r = /\//ig;
var test = "this whole line highlights incorrectly"
```

**Comment by zertosh** [comment]
Works for me. Make sure you're actually using JavaScriptNext with this file.

![vsokk](https://cloud.githubusercontent.com/assets/830952/7710991/b5070394-fe35-11e4-9c3e-58b7b5f43297.png)

**Comment by lalitkapoor** [comment]
@zertosh I accidentally added an extra slash at the end of the regex. I've updated it above. Can you try again with the update please. Thanks!

**Comment by zertosh** [comment]
Still works :/

![kclnq](https://cloud.githubusercontent.com/assets/830952/7711067/1c17a8ea-fe36-11e4-81bd-6ece0efb044d.png)

**Comment by lalitkapoor** [comment]
@zertosh thanks for taking a look. I restarted sublime and it resolved, not sure why that happened.
