### ISSUE TITLE
Add a license statement

### ISSUE THREAD

**Issue by aeschli** [Benvie/JavaScriptNext.tmLanguage#141]
Can you add a license statement? Is it ok to use your tmLanguage files in a open source project?

**Comment by aeschli** [comment]
See https://help.github.com/articles/open-source-licensing/ for more info on why this is a good thing to have.

**Comment by simonzack** [comment]
Since I made most of the commits and benvie is not responding I think I have some say in this. You're free to do whatever you want as long as you attribute the contributers & source. I'm not too familiar with this copyright stuff, would that be a Creative Commons?

**Comment by aeschli** [comment]
Check out http://choosealicense.com/. I think the MIT licence does what you want.

**Comment by simonzack** [comment]
There we go, good luck on that project of yours.

**Comment by aeschli** [comment]
Awesome, thanks a lot!
