### ISSUE TITLE
ST3, JavaScriptNext v2015.11.25.09.51.16 breaks PHP and Markdown syntaxes

### ISSUE THREAD

**Issue by podkot** [Benvie/JavaScriptNext.tmLanguage#142]
Hello. ST3 build 3095 MacOSX. All was fine just before the last update, v2015.11.25.09.51.16. Now there are a few problems:

```
Error loading syntax file "Packages/Markdown/Markdown.sublime-syntax":
Apparent recursion within a with_prototype action: 25000 context sanity limit hit
```

```
Error loading syntax file "Packages/PHP/PHP.sublime-syntax":
Apparent recursion within a with_prototype action: 25000 context sanity limit hit
```

And these syntaxes don't work. When I disable JavaScriptNext, PHP & Markdown both work as expected.

**Comment by tcauduro** [comment]
Same issue here after updating; on both windows and mac platforms.  Other syntaxes work when JavaScriptNext is disabled.

**Comment by evanemolo** [comment]
+1

**Comment by simonzack** [comment]
Strange, I've rolled back the previous commit, was that the cause? It works on my sublime 3083, are any of you guys interested in taking a look?

**Comment by podkot** [comment]
No new version in [Package Control](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax) yet. 

Also, not sure whether it can be the cause, but commit a940c4559bc7c5bdd9438fb24f076360c8e0ea32 seems to have more changes than reverted one.

**Comment by podkot** [comment]
I can confirm, another syntaxes work fine with the new v2015.11.25.18.15.38. Thank you!

**Comment by simonzack** [comment]
The issue still deserves some investigation though as the html quasi string feature would be good to have.
