### ISSUE TITLE
Conditional operator inside object literal causes inconsistent highlighting

### ISSUE THREAD

**Issue by silverwind** [Benvie/JavaScriptNext.tmLanguage#50]
`.prop :` shouldn't be highlighted here:

![hl](https://cloud.githubusercontent.com/assets/115237/4906463/2c3d5962-6459-11e4-95d1-9782556ef7d5.png)

````js
var test = { prop: (true ? a.prop : b.prop) };
````

**Comment by simonzack** [comment]
Turns out multi-line ternaries can be matched after all. There are some grouping issues, i.e. the expression before `?` and after `:` is unknown, but I think this is hardly needed.
