### ISSUE TITLE
Highlight $

### ISSUE THREAD

**Issue by Rleahy22** [Benvie/JavaScriptNext.tmLanguage#54]
Especially an issue in Angular, it would be nice if in $scope for example the $ was highlighted in the same manner that the regular JavaScript syntax highlighter handles $.

**Comment by simonzack** [comment]
It's now scoped under `variable.other.dollar.js`. You can add this to your theme to highlight it.

**Comment by malcolmocean** [comment]
@simonzack How do you actually do that? Tutorial link is fine... I was really confused when all of a sudden my lovely yellow `$scope` variables became white.

**Comment by malcolmocean** [comment]
I have reverted to an older version of the template/scheme, because the new one is borky.

**Comment by simonzack** [comment]
@malcolmocean Are you referring to the Next theme? I've added the same color and put it in italics to differentiate it from normal variables. Looks good?

**Comment by malcolmocean** [comment]
Yeah I think things are good now.
