### ISSUE TITLE
Issue with SublimeText

### ISSUE THREAD

**Issue by Hipposterous** [Benvie/JavaScriptNext.tmLanguage#6]
I get this error now when opening ASP files in SublimeText. Possible due to the change a few hours ago.

Error loading syntax file "Packages/ASP/HTML-ASP.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

https://forum.sublimetext.com/t/html-asp-sublime-syntax-error-loading-syntax-file-answered/25084

**Comment by tea3** [comment]
+1

The same error has occurred in my SublimeText3.  And it is also affected by other SyntaxHighlighter.

**Comment by harryyeh** [comment]
+1 - Affects all packages - have to disable this package for other packages to load. 

error loading syntax file Packages/markdown/markdown.extended.sublime-syntax apparent recursion within a with_prototype action 25000 context sanity limit hit

**Comment by ivanionut** [comment]
same error with [CFML!](https://github.com/jcberquist/sublimetext-cfml)

**Comment by marcosc90** [comment]
+1

**Comment by marcosc90** [comment]
I fixed this issue by updating sublime to the latest version: `Version 3.1.1, Build 3176`

In ubuntu just do the following:

```
sudo apt-get update
sudo apt-get install sublime-text
```

**Comment by Hipposterous** [comment]
SublimeText version 3.1.1 does the trick

**Comment by Hipposterous** [comment]
I spoke too soon. I closed and re-opened SublimeText and got the error again. 
I have 3.1.1, Build 3176 on Windows.
Considering the behavior, it feels like a SublimeText problem.

**Comment by tea3** [comment]
@Hipposterous My sublime text 3 also don't solved this issue.  I have 3.1.1, Build 3176 on Mac OSX.

**Comment by ibobo** [comment]
This happens to me also, I have ST 3.1.1 build 3176 on Mac OS X.

Removing the `JavaScriptNext` package fixes the issue. Please fix the problem!
