### ISSUE TITLE
class Foo extends mixin(Bar, SomeTrait)

### ISSUE THREAD

**Issue by lukescott** [Benvie/JavaScriptNext.tmLanguage#62]
The following code does not color correctly:

```
class Foo extends mixin(Bar, SomeTrait) {...}
```

Correct:
![screen shot 2015-01-14 at 1 49 13 pm](https://cloud.githubusercontent.com/assets/486224/5748373/4023783a-9bf4-11e4-86c4-ea314c185b22.png)

Incorrect (would expect it to be more like the above):
![screen shot 2015-01-14 at 1 49 00 pm](https://cloud.githubusercontent.com/assets/486224/5748385/5a4ceebc-9bf4-11e4-81af-20e06816653c.png)

As far as I can tell, this is valid syntax, and an accepted practice, as a workaround until ES7:

https://www.google.com/webhp#q=es6%20mixin%20extend%20class

**Comment by simonzack** [comment]
Since all expressions are supported in extends I've got rid of `entity.name.extends.js` since it no longer makes sense.
