### ISSUE TITLE
Sublime 3 Support

### ISSUE THREAD

**Issue by EisenbergEffect** [Benvie/JavaScriptNext.tmLanguage#67]
I didn't see this package come up in the package manager install menu for Sublime 3. Is Sublime 3 supported? If not, is there any chance of adding support for it? Or is their a manual way to install this for Sublime 3?

**Comment by simonzack** [comment]
Yes it is supported. I did a [search](https://packagecontrol.io/packages/JavaScriptNext%20-%20ES6%20Syntax) and it does say ST2/ST3, what are you typing in the package manager to find it?

But I think the summary might be a bit confusing, I don't have access to edit that. @Benvie is it possible that you can include sublime text 3 in the summary? Thanks.

**Comment by EisenbergEffect** [comment]
Ah. I missed the ST2/ST3 and just saw the summary text. I think I've got it installed...but I don't think it was called JavaScript Next. Does it appear under a different name?

**Comment by simonzack** [comment]
I don't think so, I just check my sublime and it says "Java​Script​Next" there. What does yours say?

**Comment by simonzack** [comment]
Marked as resolved since ST3 is supported.
