### ISSUE TITLE
Object keys starting with $ are treated differently

### ISSUE THREAD

**Issue by tjconcept** [Benvie/JavaScriptNext.tmLanguage#69]
```js
{
	$a: true,
	b: true,
	_c: true,
}
```

The `$a` is differently colored than the two following.

**Comment by malcolmocean** [comment]
I think this just started with a recent update. It applies to variables too, not just keys. Variables like angular's `$scope` used to be yellow like the rest of them, and now are white. I'm in the process of trying to revert my version of JSNext because this is super confusing.
