### ISSUE TITLE
No scope distinguishes function use from function definition

### ISSUE THREAD

**Issue by davidmccabe** [Benvie/JavaScriptNext.tmLanguage#70]
Thanks for making this language!

Unlike with the included Javascript language, function invocations receive the `entity.name.function` scope. This makes it so that there's no scope that a function name in a function definition possesses which the function name in a function invocation does not. Therefore, there's no way to assign a distinguished color for function names in function definitions.

**Comment by simonzack** [comment]
You can match function calls with `meta.function-call entity.name.function`. Give the `scope always` package a try.

> Thanks for making this language!

You're welcome!

**Comment by simonzack** [comment]
Closing for now, re-open if that doesn't work for you.
