### ISSUE TITLE
Strict equal (===) mistakenly scoped as assignment operator

### ISSUE THREAD

**Issue by seanCodes** [Benvie/JavaScriptNext.tmLanguage#72]
The strict equal is currently being scoped as `keyword.operator.assignment` rather than `keyword.operator.relational` like other comparison operators.

![screen shot 2015-01-23 at 4 06 46 pm](https://cloud.githubusercontent.com/assets/1609890/5885001/24ecb752-a31a-11e4-84c2-abbe25dd6963.png)

**Comment by Dashed** [comment]
@seanCodes Want to PR? :D

**Comment by simonzack** [comment]
Fix was easy enough :) PRs are always welcome!

**Comment by seanCodes** [comment]
Thanks @simonzack, I'll submit a PR next time. :)
