### ISSUE TITLE
Reserved keywords as hash keys

### ISSUE THREAD

**Issue by tjconcept** [Benvie/JavaScriptNext.tmLanguage#73]
```js
{
	default: true,
	private: true,
	public: true,
	break: true,
	other: true,
}
```

AFAIK there is not semantically difference between these hash keys, and they are all completely valid according to the spec and implementations, nonetheless "default" and "break" are colored differently, probably because they are reserved keywords.
I guess they should still be exclusively colored when used incorrectly, as in ~~`var default = true;`~~.

**Comment by zertosh** [comment]
This change has the unfortunate effect of matching the `default` keyword in a `switch` as `string.unquoted.label.js` instead of `keyword.control.switch.js`

![oquue](https://cloud.githubusercontent.com/assets/830952/6322319/9aecf66a-badf-11e4-9ac7-812cf9906fe3.png)
