### ISSUE TITLE
Dollar Sign HighLight.

### ISSUE THREAD

**Issue by ctf0** [Benvie/JavaScriptNext.tmLanguage#74]
a conitnu to https://github.com/Benvie/JavaScriptNext.tmLanguage/issues/54

`variable.other.dollar.js` HL the whole word `$scope` 
but the default JS HL `$` in a color and `scope` in another.

essentially what am after is i want to HL the `$` in the below code and leave the rest of the word intact.
```js
.controller('DetailsController', ['$scope', '$http', '$routeParams', function($scope, $http, $routeParams) {
	$http.get('js/data.json').success(function(data) {
		$scope.artists = data;
		$scope.whichItem = $routeParams.itemId;
    });
}]);
```

is there away to add support for somthing like that ?

**Comment by ctf0** [comment]
also can we make the detection for the word `this` a bit more smart like
`$(this)` HL is different than `this.something`

**Comment by simonzack** [comment]
I've added the `variable.other.dollar.js punctuation.dollar.js` scope for you angulars :)

@ctf0 Regarding the last `$(this)` I think this is a bit of a niche issue, and it adds enough complexity that the core highlighter rules would need to be changed, so I'm not interested in having that.
