### ISSUE TITLE
Support special highlight for declared variables

### ISSUE THREAD

**Issue by arendjr** [Benvie/JavaScriptNext.tmLanguage#77]
I have a feature request which is as follows: One thing I miss in Sublime's JS highlighter is giving a special color to declared variables. Compare for example:

    x = 1;

With:

    var x;
    x = 1;

In the second example, the parser should be able to detect *x* is a declared variable and highlight it accordingly.

It's a feature available in Qt Creator's JS editor and one I appreciate greatly because it makes it very easy to spot typos and other mistakes as a wrongly spelled or scoped variable would be undeclared and thus not have the proper highlighting.

I hope this is the proper place to report this issue and that your highlighter could support this feature. Thanks!

**Comment by simonzack** [comment]
I don't think this is possible, what other editoros do is to parse the javascript properly and do some static analysis on it. Theme files cannot even match across new lines, let alone parse javascript properly. You might want to look at sublime linter's jshint package instead. You'll get a yellow box around undeclared variables, with some python you could change the text's color too, I think.
