### ISSUE TITLE
Issues with explicitly specifying background color

### ISSUE THREAD

**Issue by rwaldron** [Benvie/JavaScriptNext.tmLanguage#80]
Would it be possible to eliminate the explicit background colors that are specified in the Monokai theme? The black background used by default is too harsh for my eyes, but I don't think anyone else should be forced to use _my_ preference, so I maintain a fork of JavaScriptNext.tmLanguage that removed all of the word- and character-specific background colors and uses a dark grey background for everything. Whenever Sublime updates to the latest version of JavaScriptNext.tmLanguage, I just pop open the terminal, run `fixtheme` and I'm good to go, until today. The latest version appears to have changed several things and I can't figure out how to undo them, so I'm asking for help now: please remove the word- and character-specific background colors in the Monokai theme so that user-specific background colors work correctly. To illustrate:

![](http://i.gyazo.com/99ff0f3467db25d3df364913e3b7ded9.png)

Note the black background around `constructor` and `extends` (also note that `extends` followed by a parenthetical expression is treated like concise method syntax, but that's a different bug that I will file).

That screenshot might not capture the issue as clearly as it is to see on an actually monitor, so check this out: 

![](https://dl.dropboxusercontent.com/u/3531958/monokai-background-color.jpg)

Bummer, right? 

I really don't mind maintaining my fork, but the Monokai theme needs to allow for a single user-defined background color. Consideration is appreciated :)

**Comment by simonzack** [comment]
Absolutely, the extra black backgrounds don't make much sense at all. Does the above commit fix your issue?

**Comment by rwaldron** [comment]
Thanks for taking a look at this, very much appreciated. Unfortunately, the changes don't appear to affect `constructor`. 

If I remove these lines: https://github.com/Benvie/JavaScriptNext.tmLanguage/blob/master/Monokai%20Phoenix.tmTheme#L14-L15

This is the result: 

![](http://i.gyazo.com/bae78846dc7eb543e9674ebe1e77a460.png)

**Comment by simonzack** [comment]
@rwaldron Strange, it doens't show black for me. Can you paste the code?

**Comment by rwaldron** [comment]
Turns out it's any concise method: 


```js

class Foo {
  constructor() {
  }
  method() {
  }
}
```


![](https://dl.dropboxusercontent.com/u/3531958/class-method-highlighting.jpg)

**Comment by simonzack** [comment]
I get 
![screenshot](https://cloud.githubusercontent.com/assets/628500/6427069/6982b95e-bfc9-11e4-8714-ebd2a6426846.png)

Are you sure you have the latest version? There are no backgrounds in the monokai theme anymore except for the main black background.
