### ISSUE TITLE
`extends` followed by a parenthetical expression is treated like concise method syntax

### ISSUE THREAD

**Issue by rwaldron** [Benvie/JavaScriptNext.tmLanguage#81]
![](http://i.gyazo.com/99ff0f3467db25d3df364913e3b7ded9.png)

**Comment by simonzack** [comment]
https://github.com/Benvie/JavaScriptNext.tmLanguage/commit/9534713df7290eba8fb48c16d07a3fd12875a069 appears to have fixed this.
