### ISSUE TITLE
Syntax problem

### ISSUE THREAD

**Issue by james-fray** [Benvie/JavaScriptNext.tmLanguage#83]
Here is the example:
S3 JavaScript:
![screen shot 2015-02-22 at 00 02 24](https://cloud.githubusercontent.com/assets/9897733/6315960/22e5ef44-ba28-11e4-8e97-decde469e3f2.png)

S3 JavaScriptNext:
![screen shot 2015-02-22 at 00 02 33](https://cloud.githubusercontent.com/assets/9897733/6315961/2be4a522-ba28-11e4-9b1a-80b92971d892.png)

http://ace.c9.io
![screen shot 2015-02-22 at 00 02 46](https://cloud.githubusercontent.com/assets/9897733/6315958/20bc45ba-ba28-11e4-8bf9-d45304dd512d.png)

**Comment by zertosh** [comment]
@james-fray what exactly is the problem?

**Comment by simonzack** [comment]
This isn't related to javascript next, it's probably a linter issue. Javascript next can't do squiggles.
