### ISSUE TITLE
Closing parenthesis bug

### ISSUE THREAD

**Issue by davidnormo** [Benvie/JavaScriptNext.tmLanguage#85]
When I'm closing a nested parenthesis, before another closing paraenthesis, the character won't be inserted. 
E.g. Adding a closing ")" to the call of `anotherFunction`

```
helloWorld(anotherFunction()
```
The result is the cursor moves to the other side of the existing closing parentheses. I'm expecting another ")" to be added to give:
```
helloWorld(anotherFunction())
```

Any help you can give on this one would be much appreciated!
Thanks

**Comment by simonzack** [comment]
I agree it's very annoying, but I think this is a sublime text bug (strange feature?), same thing happens in plain text. There's really nothing I can do.

**Comment by davidnormo** [comment]
Ah yeah thanks. FYI I used the [Smart Match](https://github.com/ccampbell/sublime-smart-match) package to fix it.

**Comment by simonzack** [comment]
Nice find, I'll keep that in mind, thanks!
