### ISSUE TITLE
first character is a different color if capitalized.

### ISSUE THREAD

**Issue by Raynos** [Benvie/JavaScriptNext.tmLanguage#88]
![img](http://i.imgur.com/haCay0j.png)

The first character if its capitalized is now a different color. This is a recent breaking change ( last 12 hours ).

I'll temporarily switch to the javascript next monokai theme as that one doesn't have this artifact.

**Comment by simonzack** [comment]
Oops forgot a `\b`. Hope it's fixed now.

**Comment by Raynos** [comment]
noice. Fixed it.
