### ISSUE TITLE
Color scheme Next for `else if` looks odd.

### ISSUE THREAD

**Issue by Raynos** [Benvie/JavaScriptNext.tmLanguage#90]
![else if](http://i.imgur.com/3Dfpebb.png?1)

I remember that previously the `else if` was not italic or colored differently, nor was the first word past it colored differently.

I do not know if this was a recent regression though.

**Comment by simonzack** [comment]
I think this is the same problem I've fixed on the last commit, can you updated and try again?

**Comment by Raynos** [comment]
Your right, The last commit fixed it.

Thanks!

**Comment by Raynos** [comment]
@simonzack thanks for all the work and fast responses :)

If I find anything else I will report it here! Loving javascript next.

**Comment by simonzack** [comment]
Great to hear you appreciate it, thanks!
