### ISSUE TITLE
Does not appear in Syntax Menu

### ISSUE THREAD

**Issue by speg** [Benvie/JavaScriptNext.tmLanguage#91]
In Sublime Text 3 I cannot find JavaScript next in the syntax menu. It works fine if I choose it from the Control+Shift+P prompt. This is a problem because I cannot set it as the default syntax for specific filetypes.

**Comment by simonzack** [comment]
Works for me. Can you try a clean install?

**Comment by simonzack** [comment]
Closed since works for me. Feel free to re-open if the issue's still there.
