### ISSUE TITLE
Single line comments in arrays

### ISSUE THREAD

**Issue by morkro** [Benvie/JavaScriptNext.tmLanguage#98]
Hey,

first of all you did a nice job! 
I already love the theme but stumpled upon something I'm not sure if it's intended or a bug.

Single line comments inside of an array will break syntax highlighting, whereas multi line comments won't.

```javascript
const arr = [
	/* Comment */
	'foo',
	'bar',
	'baz', /* Comment */
	/* 'foo' */
];

// Will fail highlighting:
const arr2 = [
	// Comment
	'foo',
	'bar',
	'baz', // Comment
	// 'foo'
];
```

![screen shot 2015-03-09 at 11 55 31](https://cloud.githubusercontent.com/assets/2461956/6553653/36c77726-c653-11e4-8c73-ed031686a7ad.png)

Is this intended?

**Comment by simonzack** [comment]
Here's what I see:

![screenshot](https://cloud.githubusercontent.com/assets/628500/6553723/fc07f232-c6a7-11e4-91f7-8ea01afb52f1.png)

Your first case works fine too.

Sure you're on the latest version?

**Comment by morkro** [comment]
Updating and reopening Sublime Text did the trick! 
Thanks for your time and sorry for opening this stupid bug ;)
